# Generated by Django 4.1.7 on 2023-05-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('alice', models.CharField(max_length=65536, null=True)),
                ('bob', models.CharField(max_length=65536, null=True)),
                ('alice_key', models.JSONField(null=True)),
                ('alice_table', models.JSONField(null=True)),
                ('message', models.CharField(max_length=65536, null=True)),
            ],
        ),
    ]
